# SPDX-FileCopyrightText: 2025 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "uniflow"
SPDX-PackageSupplier = "Uniflow Devs"
SPDX-PackageDownloadLocation = "https://github.com/uniflow/uniflow"

[[annotations]]
path = [
   ".github/**"
 , ".clang-format"
 , ".editorconfig"
 , ".gitattributes"
 , ".gitignore"
 , "cspell.json"
 , "sonar-project.properties"
 , "cmake/vcpkg.json.in"
 , "**/*.md"
 , "docs/**"
 , "deploy/linux/flatpak/**"
 , "deploy/linux/org.uniflow.uniflow.metainfo.xml"
 , "deploy/windows/wix-patch.xml.in"
 , "src/apps/uniflow-client/uniflow-client.exe.manifest"
 , "src/apps/uniflow-core/uniflow-core.exe.manifest"
 , "src/apps/uniflow-server/uniflow-server.exe.manifest"
 , "src/apps/res/manpage.txt"
 , "src/apps/res/uniflow.plist.in"
 , "src/apps/res/entitlements-dev.plist"
 , "translations/*.ts"
]
SPDX-FileCopyrightText = "Uniflow Developers"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
   "deploy/mac/dmg-background.tiff"
 , "deploy/mac/dmg-volume.icns"
 , "deploy/linux/org.uniflow.uniflow.png"
 , "deploy/windows/wix-banner.png"
 , "deploy/windows/wix-dialog.png"
 , "src/apps/res/icons/uniflow-**/apps/64/uniflow*.svg"
 , "src/apps/res/image/welcome.png"
 , "src/apps/res/Uniflow.icns"
 , "src/apps/res/uniflow.ico"
 , "src/apps/res/uniflow.qrc"
]
SPDX-FileCopyrightText = "Uniflow Developers"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/apps/res/icons/uniflow-**/**/**/**.svg"
SPDX-FileCopyrightText = "Kde Breeze Icons"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = "src/apps/res/icons/uniflow-**/index.theme"
SPDX-FileCopyrightText = "Chris Rizzitello <sithlord48@gmail.com>"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = [
   "src/lib/gui/MainWindow.ui"
 , "src/lib/gui/dialogs/*.ui"
]
SPDX-FileCopyrightText = "Uniflow Developers"
SPDX-License-Identifier = "GPL-2.0-only WITH LicenseRef-OpenSSL-Exception"
